name: Prettier

# This action works with pull requests and pushes
on:
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing dependencies
        run: npm install
      - name: Checking if code is pretty
        run: npm prettier --check *.[ts,js]
