name: ts-standard

on:
  push:
    branches:
      - ts_standrd_tool
  pull_request:
    branches:
      - ts_standrd_tool
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Runing ts-standard on files  
        run: npm install --save-dev ts-standard
      - name: run standard
        run: ts-standard      

     
