name: ts-standard

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        node-version: [18.13.0]

    steps:
      - uses: 'actions/checkout@v3.0.2'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: 'actions/setup-node@v3.5.0'
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Install Dependencies'
        run: 'npm install --save-dev ts-standard'
      - run: 'standard'
       

     
